### ISSUE TITLE
Compile properties as constants

### ISSUE THREAD

**Issue by jasonmoore2k** [sbt/sbt-buildinfo#127]
Rather than
`
case object BuildInfo {
  val version: String = "0.1.0-SNAPSHOT"
}
`
could we do
`
case object BuildInfo {
  final val version = "0.1.0-SNAPSHOT"
}
`
One reason for doing this would be so that these properties could be used as annotation arguments.

**Comment by dwijnand** [comment]
So the reason that that would be useable as an annotation argument is because it becomes a constant literal that gets inlined at compile time.

The things about inlining is that you should really _not_ inline from a library to another library. Inlining should only happen in applications.

Therefore I think this should be possible, but only as an opt-in.

WDYT?

**Comment by jasonmoore2k** [comment]
Good point about use within library vs exposing it to another. I hadn't considered that.

For context I'm looking to use this at the 'edge of the world' (cli) not in a library that will be packaged into other apps.

An opt-in sounds like a good approach to leave existing behavior as-is.

**Comment by magneticflux-** [comment]
Has there been any progress on this issue? I'm also using this for a CLI project that uses annotations.
