### ISSUE TITLE
adding play version jvm version and jvm args

### ISSUE THREAD

**Issue by chenbekor** [sbt/sbt-buildinfo#64]
this plugin is super!

suggestion - would be great if you incorporate the example provided in https://github.com/sbt/sbt-buildinfo/issues/22   in the readme (home page of the gut repo)

also - can you please add support or play version JVM version and JVM args ?

again thank you!!

**Comment by AtkinsChang** [comment]
You can obtain play version via `play.core.PlayVersion.current` and put it into plugin settings.
JVM version and args depends on your runtime vm. You can obtain it by `java.lang.management.RuntimeMXBean`.

**Comment by reid-spencer** [comment]
As a side note, and general policy, I think that sbt-buildinfo should NOT provide information that is otherwise available at runtime but only information that is only accessible at build time. 

So, per this request, It might be useful to know the version of the JDK that ran the compiler that compiled the project that any-buildings is plugged into.

**Comment by eed3si9n** [comment]
You should be able to implement this using existing sbt-buildinfo by defining a custom setting.
