### ISSUE TITLE
RFE: don't update the file if there are no changes

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-buildinfo#96]
in ensime-server we do this

```
enablePlugins BuildInfoPlugin settings (
        buildInfoPackage := organization.value,
        buildInfoKeys += BuildInfoKey.action("gitSha")(Try("git rev-parse --verify HEAD".!! dropRight 1) getOrElse "n/a"),
        buildInfoOptions += BuildInfoOption.BuildTime
      )
```

which results in a new .scala file (effectively an updated timestamp) on every compile or test run, which slows down the dev cycle.

It would be good if the file was not updated unless there are changes.

**Comment by Taig** [comment]
I am facing the same issue. Especially in multi-project setups this gets pretty annoying and time-consuming. An option allowing to only run buildinfo generation for clean builds / when the generated file doesn't exist yet would solve that for me.

**Comment by LogicalTime** [comment]
This is really bad with ScalaJS. It means fast or full optimization must be run every time.  What task do we look at to see if there are compile changes?

**Comment by fommil** [comment]
I have a workaround something along the lines of

```
buildInfoOptions := Seq(BuildInfoOption.ToJson) ++ sys.env.get("CI").toList.map(_ => BuildInfoOption.BuildTime)
```

adapt to your needs. It's the build time option that messes up the incremental compiler's calculations.

**Comment by fommil** [comment]
better

```scala
    buildInfoOptions ++= {
      if (sys.env.contains("SBT_IGNORE_BUILDTIME")) Nil
      else Seq(BuildInfoOption.BuildTime)
    }
```

**Comment by dwijnand** [comment]
I think this issue is invalid. Time is always changing and `BuildInfoOption.BuildTime` will make sure that it's always up to date.

So you can either opt-out with the workaround above, or if you want to use a cached value of "current time" I'd suggest defining a setting key that initialises a stable (and instantly stale) date, similar to how sbt-dynver does: https://github.com/dwijnand/sbt-dynver/blob/v2.0.0/src/main/scala/sbtdynver/DynVerPlugin.scala#L13
